Add notification rate limit info to settings
home-assistant/android pull request #1015
Opened 2020-10-07 03:18 UTC by dshokouhi

This PR adds a preference that contains the notification rate limit data.  This preference is only visible if the user is on the `full` flavor and if the call was successful.  One thing to note for some reason the call does not return any data when we first visit settings, its only subsequent visits does the call save.

![image](https://user-images.githubusercontent.com/1634145/95283237-264cd300-0810-11eb-9cc9-0c076f990d78.png)

2020-10-07 14:01 UTC, dshokouhi commented
Marked as draft while I move logic to `integrationService`

2020-10-08 13:56 UTC, JBassett requested changes

2020-10-08 13:56 UTC, JBassett commented on common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationService.kt
> +    ): HashMap<String, *>
Rather than returning a Hash Map here we should return our own data class.

2020-10-08 13:56 UTC, JBassett commented on common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
> +    override suspend fun getNotificationRateLimits(): HashMap<String, *>? {
This should return an actual data class rather than a hashmap.

2020-10-08 13:56 UTC, JBassett commented on common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
> +        val requestBody = mapOf("push_token" to pushToken)
This request should also be a data class.

2020-10-08 13:56 UTC, JBassett commented on app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenterImpl.kt
> +            integrationUseCase.getNotificationRateLimits()!!
If this service call fails we will crash the app.  We should add some error handling.

2020-10-08 18:01 UTC, JBassett approved these changes

2020-10-08 18:05 UTC, merged