Allow notifications to use the alarm stream
home-assistant/android pull request #1019
Opened 2020-10-07 20:10 UTC by dshokouhi

Fixes: #561 

The best way to make sure a notification stays as expected while also respecting Android 8+ channels lets use a specific channel to bypass the devices ringer mode.  The notification will make a sound (regardless if the device is on vibrate/silent) and behave much like an alarm, the stream will stop once the user interacts with their device. The default sound will be the default alarm which may be enough for most users.  There is also code to support legacy devices too, we are just reading the channel name and changing the stream accordingly.

Example:

```
message: This is the alarm stream
data:
  channel: alarm_stream
```

2020-10-07 21:47 UTC, dshokouhi commented
Thought of another interesting use case for this.....users can use HA to create their own alarms on the device entirely controlled from HA :)  Don't even need to touch an alarm app, just set it in HA and have the house wake you up as needed.

2020-10-08 14:12 UTC, JBassett requested changes

2020-10-08 14:12 UTC, JBassett commented on app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt
> +        }
We should break the sound handling into a method like the rest of the items.  I think the category can go in there for now as well.

2020-10-08 15:20 UTC, JBassett approved these changes

2020-10-08 15:20 UTC, merged

2021-01-06 23:09 UTC, cwalger commented
Hello, this looked promising but I am using a Samsung S10e and the latest version of the app from the play store and the notifications do not play a sound when the phone is set to vibrate or to mute.  When my phone is set to sound, the notifications do use the alarm ringtone, so it is partially working.  Thank you

2021-01-06 23:12 UTC, dshokouhi commented
@cwalger please do not use merged PRs to discuss issues, there is already an open issue for this that you can read through and provide feedback and logs as requested: https://github.com/home-assistant/android/issues/1186

2021-01-06 23:20 UTC, cwalger commented
Sorry, noted, and thank you for the link.  I read through a few threads elsewhere that pointed to this as the solution.