Fix app crash on invalid chronometer notification data
home-assistant/android pull request #1185
Opened 2020-11-10 17:54 UTC by Hypfer

## Summary

This PR wraps handling of chronometer notifications in a try/catch to prevent the app from crashing when invalid data is received.

## Any other notes

This PR is pretty basic and only prevents a hard crash. There's definitely room for improvement regarding usability
It might make sense to mark invalid notifications in the notification log or something like that

2020-11-10 17:57 UTC, dshokouhi commented
In what cases does this fail? we should be preventing bad data if we can.

2020-11-10 17:58 UTC, dshokouhi commented
please also post the crash log too

2020-11-10 17:59 UTC, Hypfer commented
Behold my inability to understand when and how to use templates
```yaml
title: "Test"
message: "Test2"
data:
  chronometer: true
  when: "{{ (as_timestamp(now()) + 60) | round }}"
```

Exception from logcat:
```
FATAL EXCEPTION: main
Process: io.homeassistant.companion.android, PID: 29490
java.lang.NumberFormatException: For input string: "{{ (as_timestamp(now()) + 60) | round }}"
 at java.lang.Long.parseLong(Long.java:594)
 at java.lang.Long.parseLong(Long.java:636)
 at io.homeassistant.companion.android.notifications.MessagingService.handleChronometer(MessagingService.kt:457)
 at io.homeassistant.companion.android.notifications.MessagingService.sendNotification(MessagingService.kt:433)
 at io.homeassistant.companion.android.notifications.MessagingService$onMessageReceived$$inlined$let$lambda$6.invokeSuspend(MessagingService.kt:210)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
 at android.os.Handler.handleCallback(Handler.java:873)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:193)
 at android.app.ActivityThread.main(ActivityThread.java:6923)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
```

2020-11-10 18:05 UTC, dshokouhi requested changes
Its good to make sure the app doesn't crash but its better to prevent the error and get the proper defaults :)

2020-11-10 18:05 UTC, dshokouhi commented on app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt
> +            val notificationWhen = data[WHEN]?.toLong()?.times(1000) ?: 0
```suggestion
            val notificationWhen = data[WHEN]?.toLongOrNull()?.times(1000) ?: 0
```

This should make sure it doesn't fail and defaults to 0 properly

2020-11-12 03:06 UTC, JBassett approved these changes

2020-11-12 03:19 UTC, merged