Update CoverControl.kt
home-assistant/android pull request #1462
Opened 2021-03-28 11:25 UTC by Sissi91

## Summary

In the Android Power Menu it is now possible to set the position of covers. On plus of that, there is also a change made, that the cover change direction if it is closing at the moment you toggle the button.

## Screenshots

![image](https://user-images.githubusercontent.com/34167143/112750399-b3efcb00-8fc8-11eb-9b28-08b35aebe6f5.png)

## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#

## Any other notes

2021-03-28 11:25 UTC, homeassistant commented
Hi @Sissi91, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;android#1462).

Once you do that we will be able to review and accept this pull request.

Thanks!

2021-03-28 15:48 UTC, dshokouhi approved these changes
Looks good to me!

2021-03-28 17:21 UTC, JBassett requested changes

2021-03-28 17:21 UTC, JBassett commented on app/src/main/java/io/homeassistant/companion/android/controls/CoverControl.kt
> +                    )
We need to pull the latest changes to include the popup menu changes.

2021-03-29 00:25 UTC, JBassett approved these changes

2021-03-29 00:25 UTC, merged