Wear os authentication
home-assistant/android pull request #1691
Opened 2021-08-23 21:02 UTC by leroyboerefijn

## Summary

In this PR a proof-of-concept for authentication on wear os devices. Note that a few changes needed to be made compared to the android app authentication:

- Since resources are very limited on wear OS devices, I decided to omit LaunchActivity. Instead, the checks are done in HomeActivity. This should speed up the launch of HomeActivity (the main flow) slightly
- Since Wear OS devices do not support WebViews, it was not possible to use the default authentication web page and api. Instead, I directly tap into auth/login_flow
- If an android device is connected, it will automatically share the url of the HA instance. This saves the user a lot of annoying typing. It is always possible for the user to manually enter an url if needed.

On HomeActivity, a proof of connection/authentication is given, by loading the home assistant version and the number of instances from the server.

## Screenshots

![onboarding](https://user-images.githubusercontent.com/34075651/130518703-9839afc1-8694-4001-9d76-2205208f4181.jpg)
![login](https://user-images.githubusercontent.com/34075651/130518742-ed0e5b33-c72e-45a3-9794-d009e447b4cd.png)
![integration](https://user-images.githubusercontent.com/34075651/130518747-48ec3890-c64c-4c2c-9ed2-e95eeb4b4ab8.png)
![home](https://user-images.githubusercontent.com/34075651/130518753-99d08180-6006-4377-9cb5-005d95df02b4.png)

## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#

## Any other notes

Once the authentication is implemented, next steps will be adding functionality to the wear OS app:

- Activating scenes
- Providing sensor information
- Controlling entities

2021-09-04 15:14 UTC, leroyboerefijn commented
@JBassett do you think you could have a look at this PR?  Please let me know if it is too big and needs splitting!

2021-09-10 18:59 UTC, hkusulja commented
Can this be the same Android app, with same one on the store, with app manifest for wear os also.
In case it goes to internet through bluetooth and phone, it could share / use same app config (url's, authentication etc.) ?

2021-09-10 19:17 UTC, dshokouhi commented
> Can this be the same Android app, with same one on the store, with app manifest for wear os also.
> In case it goes to internet through bluetooth and phone, it could share / use same app config (url's, authentication etc.) ?

you might want to familiarize yourself with how  a standalone app works

https://developer.android.com/training/wearables/overlays/independent-vs-dependent#identify

data can be still be sent from phone to app but the intention is that everything you can do on the phone can also be done on the watch without needing the phone.

2021-09-10 20:07 UTC, JBassett requested changes

2021-09-18 10:03 UTC, leroyboerefijn commented on common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
> +        Log.d(TAG, urlRepository.getApiUrls().toString())
Agree, I used this for debugging. Have removed it now

2021-09-18 10:03 UTC, leroyboerefijn commented on wear/build.gradle.kts
> +    }
You're right indeed, removed product flavors

2021-09-18 10:03 UTC, leroyboerefijn commented on wear/src/main/java/io/homeassistant/companion/android/onboarding/viewHolders/ManualSetupViewHolder.kt
> +        (v.layoutParams as ViewGroup.MarginLayoutParams).topMargin = marginTop
This does not look great indeed, I removed the margin and added an additional header. This makes it more clear that this is a distinct option

2021-09-18 10:33 UTC, leroyboerefijn commented
I don't understand how this error suddenly occurred during the test:

ManualSetupPresenterImplSpec > presenter > on click ok with valid url > io.homeassistant.companion.android.onboarding.manual.ManualSetupPresenterImplSpec.should save the url FAILED
    java.lang.AssertionError at ManualSetupPresenterImplSpec.kt:39
        Caused by: java.lang.AssertionError at ManualSetupPresenterImplSpec.kt:39

2021-09-30 20:46 UTC, Chaphasilor commented
hey @leroyboerefijn did you figure out what caused the error? :)

> I don't understand how this error suddenly occurred during the test

I'd love to see this PR get merged, so that actual feature-development could begin! :D

2021-09-30 20:49 UTC, dshokouhi commented
The failure is a random test failure, its safe to ignore as every PR is hitting it.  As of now this PR is waiting for another round of review to continue.

2021-10-01 00:41 UTC, JBassett approved these changes

2021-10-01 00:41 UTC, merged

2021-10-01 05:41 UTC, leroyboerefijn commented
Thanks for figuring it out @dshokouhi , I was on a holiday!