Allow favorite entities to be dragged and dropped for reordering from phone settings
home-assistant/android pull request #1963
Opened 2021-11-23 22:32 UTC by dshokouhi

## Summary

Adds drag and drop for re-ordering the favorites on the Wear OS home screen. Also bumps a few libraries.

Still want to clean up the Phone UI a bit and maybe add friendly name and an icon.

As of now for some reason Wear is not saving the correct order eventhough it is retrieving the correct order per the logs.

From wear to phone
```
2021-11-23 14:09:43.213 11070-11070/io.homeassistant.companion.android.debug D/PhoneSettingsListener: Favorites: [input_boolean.bedroom_fan, input_boolean.cat_litter_cleaned, input_boolean.bedroom_curtains, input_boolean.bedroom_humidifier]
```

Then back to wear from phone (taken from app configuration hence the missing package name)
```
11-23 14:09:28.481  9762  9762 D SettingsWearViewModel: Favorites: [input_boolean.cat_litter_cleaned, input_boolean.bedroom_curtains, input_boolean.bedroom_humidifier, input_boolean.bedroom_fan]
```

Video of drag and drop in action: https://photos.app.goo.gl/iYihc3BGKg7fNbXu5

## Screenshots

## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#

## Any other notes

Marked as draft until the issue with saving the order is corrected, if anyone can see my fault here would greatly appreciate any help :)

2021-11-24 05:28 UTC, dshokouhi commented
So I tried a few things here like clearing out favorites and attempting to save the new order. It seems that the shared preferences Set String just doesn't support this as its not an ordered set. I think our options may be to convert the Set to a String and store that or wait for the DB to be ready and just store there. Storing as a string feels like a hack and it won't play nice with the `move()` function currently being used. Open to other ideas but I think we may need to wait for the DB and then store the position there.

2021-11-24 06:06 UTC, leroyboerefijn commented
I ran in the same issue for the shortcuts tile. Indeed you can only save a set, which doesn't have an order. My solution was also to save it as a string, which indeed is a temporary hack

2021-11-24 16:45 UTC, dshokouhi commented
Hmm doesn't seem like there is an easy way to convert the shared preference to a string unless I am missing something. I suppose in the meantime we can have 1 Set in there and control the order in a string until we can import to the DB.  Unless we want to make a breaking change and have users start over but I would rather do that one time with the DB (if we have to which I doubt is necessary there).

2021-11-28 03:12 UTC, dshokouhi commented
Ok everything is mostly functional. I say mostly because I am hitting a few odd issues:

1. Sometimes the list forwarded to the phone is not correct but if we back out to main settings and come back it loads fine
2. The flow of favorites is not constantly updating as the DB is changing
3. After adding favorites the list is duplicated until we resume the activity

2021-11-28 13:39 UTC, JBassett requested changes
I think we should stop passing a string around and start using the DAO and converting it to JSON.  I think once we clean that up it might be easier to see where the problem is.

2021-11-28 13:39 UTC, JBassett commented on wear/src/main/java/io/homeassistant/companion/android/phone/PhoneSettingsListener.kt
>                          }
`forEachIndexed`

2021-11-28 17:50 UTC, dshokouhi commented on app/src/full/java/io/homeassistant/companion/android/settings/SettingsWearViewModel.kt
>      }
yea no idea why this was here :)

2021-11-28 17:51 UTC, dshokouhi commented on common/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
> +                database.execSQL("CREATE TABLE IF NOT EXISTS `favorites` (`id` TEXT NOT NULL, `position` INTEGER NOT NULL)")
So I had that set in the Dao but not in AppDatabase, this is added now. I will also remove `NOT NULL` from the position

2021-11-29 02:11 UTC, dshokouhi commented on wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt
> +            favoritesDao.getAll()?.forEach {
I tried `forEachIndexed` but it was causing a crash the moment I clicked on add/remove favorites. when I switch back to `forEach` it no longer crashes and performs as expected

2021-12-09 01:52 UTC, JBassett approved these changes

2021-12-09 01:52 UTC, merged