Wear redesign
home-assistant/android pull request #1970
Opened 2021-11-27 12:52 UTC by leroyboerefijn

## Summary
The `MainView` has been redesigned based on the discussion in #1795:

- Kept favorites list at the top
- Moved other entities behind a menu, sorted on domains

Note that I see this redesign as a pre-requisite for Area support

In addition, I made some general design changes to better align with Material Design guidelines. Finally, I implemented a `MaterialTheme` to better manage colors used in compose. Sorry if the PR has become a bit large!

## Screenshots
Main view starts with favorites:
![Screenshot_20211127_134215_debug](https://user-images.githubusercontent.com/34075651/143681961-e2e487d3-c1e5-4f2b-8191-351e66b74fb2.png)

Then comes a menu to select entities:
![Screenshot_20211127_134224_debug](https://user-images.githubusercontent.com/34075651/143681971-6f2e82cd-7f29-41ed-a1c7-94a643022c24.png)

For example, the Scenes menu:
![Screenshot_20211127_134238_debug](https://user-images.githubusercontent.com/34075651/143681986-322df1c9-743d-46b9-9631-74facbdd75ee.png)

And on the bottom, the logout `Chip` has been moved to the settings menu:
![Screenshot_20211127_134232_debug](https://user-images.githubusercontent.com/34075651/143682003-12f339e0-9899-45f4-90d1-6607406b7e2a.png)

## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#

## Any other notes

2021-11-27 16:36 UTC, dshokouhi commented
This should fix #1910 as we are moving the loading of all entities to another screen meaning the homescreen is now where users can enable/disable the entities they want.

This should also solve #1885 as the categories have been moved off the homescreen.

The disabling and reordering should be focused on favorites since that is what we consider user customizable while the loading of entities is much like the states tab where we see everything.

Great work will try to take a peak at the APK later today :)

2021-11-27 17:07 UTC, dshokouhi commented
Ok got some time to test. I am seeing a couple of crashes here and there with the same stack trace. I was able to get the entities to load once and set favorites but after attempting to re-open the app I got this same crash multiple times. In fact I havent been able to load the app after setting favorites.

```
2021-11-27 09:04:14.319 733-747/? E/ActivityManager: ANR in io.homeassistant.companion.android.debug
    PID: 24055
    Reason: Broadcast of Intent { act=android.intent.action.TIME_TICK flg=0x50200014 (has extras) }
    Load: 0.0 / 0.0 / 0.0
    CPU usage from 52171ms to 0ms ago (2021-11-27 09:03:17.850 to 2021-11-27 09:04:10.020):
      5% 733/system_server: 3.2% user + 1.8% kernel / faults: 3436 minor 12 major
      1% 515/surfaceflinger: 0.6% user + 0.3% kernel / faults: 790 minor 3 major
      0.9% 306/mmcqd/0: 0% user + 0.9% kernel
      0.8% 2264/adbd: 0.1% user + 0.6% kernel / faults: 25540 minor
      0.7% 493/android.hardware.sensors@1.0-service: 0.3% user + 0.4% kernel / faults: 5239 minor
      0.3% 19934/com.google.android.gms.persistent: 0.2% user + 0.1% kernel / faults: 2875 minor 16 major
      0.3% 485/android.hardware.graphics.composer@2.1-service: 0.1% user + 0.1% kernel / faults: 104 minor
      0.2% 19474/com.google.android.wearable.app: 0.1% user + 0.1% kernel / faults: 1459 minor
      0.3% 23478/com.nike.plusgps: 0.2% user + 0.1% kernel / faults: 1233 minor 260 major
      0.2% 23251/VosTXThread: 0% user + 0.2% kernel
      0.1% 23252/VosRXThread: 0% user + 0.1% kernel
      0.1% 7/rcu_preempt: 0% user + 0.1% kernel
      0.1% 10/rcuop/0: 0% user + 0.1% kernel
      0.1% 419/logd: 0% user + 0% kernel / faults: 35 minor
      0% 23244/mdss_fb0: 0% user + 0% kernel
      0.1% 23597/kworker/u8:5: 0% user + 0.1% kernel
      0% 23459/kworker/u8:2: 0% user + 0% kernel
      0% 197/kgsl_worker_thr: 0% user + 0% kernel
      0% 330/core_ctl/0: 0% user + 0% kernel
      0% 524/modem_IPCRTR: 0% user + 0% kernel
      0% 22442/kworker/0:2: 0% user + 0% kernel
      0% 3/ksoftirqd/0: 0% user + 0% kernel
      0% 497/android.hardware.wifi@1.0-service: 0% user + 0% kernel / faults: 353 minor
      0% 2862/sugov:0: 0% user + 0% kernel
      0% 22107/kworker/u8:4: 0% user + 0% kernel
      0% 23250/VosMCThread: 0% user + 0% kernel
      0% 23759/kworker/1:0: 0% user + 0% kernel
      0% 23892/logcat: 0% user + 0% kernel / faults: 73 minor
      0% 25/migration/2: 0% user + 0% kernel
      0% 29/rcuop/2: 0% user + 0% kernel
      0% 33/migration/3: 0% user + 0% kernel
      0% 114/vsync_retire_wo: 0% user + 0% kernel
      0% 469/zygote: 0% user + 0% kernel / faults: 362 minor
      0% 512/lmkd: 0% user + 0% kernel
      0% 581/statsd: 0% user + 0% kernel / faults: 162 minor
      0% 584/wificond: 0% user + 0% kernel / faults: 36 minor
      0% 871/com.google.android.inputmethod.latin: 0% user + 0% kernel / faults: 163 minor 1 major
      0% 10738/com.fossil.wearables.batterysaver: 0% user + 0% kernel
      0% 17666/com.android.vending: 0% user + 0% kernel / faults: 611 minor 123 major
      0% 23582/kworker/2:0: 0% user + 0% kernel
      0% 23920/kworker/u8:1: 0% user + 0% kernel
      0% 13/migration/0: 0% user + 0% kernel
      0% 18/ksoftirqd/1: 0% user + 0% kernel
      0% 21/rcuop/1: 0% user + 0% kernel
      0% 26/ksoftirqd/2: 0% user + 0% kernel
      0% 34/ksoftirqd/3: 0% user + 0% kernel
      0% 115/mdp3_ppp: 0% user + 0% kernel
      0% 269/irq/237-usbin-c: 0% user + 0% kernel
      0% 347/kworker/1:1H: 0% user + 0% kernel
      0% 420/servicemanager: 0% user + 0% kernel / faults: 16 minor
      0% 421/hwservicemanager: 0% user + 0% kernel / faults: 145 minor
      0% 426/vendor.qti.hardware.sidekickgraphics@1.1-service: 0% user + 0% kernel / faults: 1 minor
      0% 460/jbd2/mmcblk0p38: 0% user + 0% kernel
      0% 468/netd: 0% user + 0% kernel / faults: 66 minor
      0% 488/android.hardware.light@2.0-service: 0% user + 0% kernel
      0% 490/android.hardware.memtrack@1.0-service: 0% user + 0% kernel / faults: 54 minor
      0% 492/android.hardware.power@1.0-service: 0% user + 0% kernel / faults: 1 minor
      0% 23253/wlan_logging_th: 0% user + 0% kernel
      0% 27415/com.fossil.wearables.watchfaces: 0% user + 0% kernel / faults: 211 minor
     +0% 24055/io.homeassistant.companion.android.debug: 0% user + 0% kernel
    33% TOTAL: 25% user + 2.9% kernel + 4.4% iowait + 0.4% irq + 0.2% softirq
    CPU usage from 61ms to 679ms later (2021-11-27 09:04:10.081 to 2021-11-27 09:04:10.699):
      174% 24055/io.homeassistant.companion.android.debug: 166% user + 7.7% kernel / faults: 1063 minor
        100% 24055/n.android.debug: 93% user + 7.7% kernel
        73% 24066/HeapTaskDaemon:

```

2021-11-27 19:01 UTC, leroyboerefijn commented
Hmmm weird! I didn't get this myself, but also haven't tried changing the favorites myself. I'll have to check if I broke something

2021-11-28 13:53 UTC, JBassett requested changes
Need to rebase/merge to the latest.

2021-11-28 13:53 UTC, JBassett commented on wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt
>              }
I would do this after the loop rather than after each iteration since this is just looping through a known list.

2021-11-29 01:51 UTC, dshokouhi commented
> Hmmm weird! I didn't get this myself, but also haven't tried changing the favorites myself. I'll have to check if I broke something

so I just saw the same crash in another branch I am in, surprisingly it also happens at the same location so doesn't seem to be related to this PR :)

2021-11-29 20:32 UTC, leroyboerefijn commented
This was a tricky rebase, but everything seems to work correctly. Please have a look again :)

2021-11-29 20:37 UTC, leroyboerefijn commented
> so I just saw the same crash in another branch I am in, surprisingly it also happens at the same location so doesn't seem to be related to this PR :)

Ah good to know! Could this be related to #1974 ? And I suppose we will fix this is a separate PR then?

2021-11-30 02:04 UTC, JBassett approved these changes

2021-11-30 02:04 UTC, merged

2021-11-30 05:01 UTC, dshokouhi commented
> Ah good to know! Could this be related to #1974 ? And I suppose we will fix this is a separate PR then?

No #1974 is a separate issue which I have resolved in #1963, we will have to see if it shows up again and see what the proper path to reproduce is then