Updated exoplayer version from 2.15.1 to r.2.16.1
home-assistant/android pull request #2144
Opened 2022-01-14 04:47 UTC by BFK78

## Summary

## Screenshots

## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#

## Any other notes

2022-01-14 04:47 UTC, homeassistant commented
Hi @BFK78, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;android#2144).

Once you do that we will be able to review and accept this pull request.

Thanks!

2022-01-14 05:08 UTC, dshokouhi commented on app/build.gradle.kts
> +    implementation("com.google.android.exoplayer:exoplayer-core:r2.16.1")
Not sure if the `r` should be there. According to Android Studio its just the number that is changing. Also `cronet` has an update as well. I also see some deprecations in the changelog, have you tested to make sure its working properly? 

![image](https://user-images.githubusercontent.com/1634145/149454811-797c711f-6bbd-4d1b-9ff4-098958a6c45a.png)

2022-01-21 16:53 UTC, dshokouhi requested changes
In order to continue with this PR it now needs to be rebased and updated to match the new format

2022-05-30 19:46 UTC, JBassett commented
Upgraded in https://github.com/home-assistant/android/pull/2556

2022-05-30 19:46 UTC, closed without merging