Migrate manage widget settings page to compose
home-assistant/android pull request #2189
Opened 2022-01-24 02:04 UTC by dshokouhi

## Summary

Just migrating the page to compose so we are no longer on preferences.  Kept the design mostly the same except there is no summary anymore. I couldnt think of a good design for that so decided to stick with `TextButton` for now.

## Screenshots

![image](https://user-images.githubusercontent.com/1634145/150710357-f6b085e8-f8b5-409c-a0b0-a572c5e58467.png)

## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#

## Any other notes

2022-01-24 11:34 UTC, jpelgrom reviewed
I am not sure using regular text for headings and `TextButton`s for each widget is the right way forward, especially when you lots of widgets this de-emphasizes the headings and the buttons have a minimum width + padding which can break up the list*. Using the previous style works well when removing the subtitle, and is a pattern you frequently see in for example the settings app.
![image](https://user-images.githubusercontent.com/8148535/150775705-98cea7b9-569a-4a4e-b607-9087b7bcb26b.png)

\* For example in your screenshot, the distance between the entity state widgets buttons is larger than the distance between a button and a heading. The text for the "test" widget is indented because of the minimum width. "alarm test" is an entity state widget but visually it is closer to the media player widgets.

2022-01-24 11:34 UTC, jpelgrom commented on app/src/main/java/io/homeassistant/companion/android/settings/widgets/views/ManageWidgetsView.kt
> +                Text(stringResource(id = R.string.list_button_widgets))
I know this hasn't changed, but the "List of" part of the string feels unnecessary and using "Button widgets", "Entity state widgets", etc as headings also work.

2022-01-24 18:57 UTC, dshokouhi commented
@jpelgrom  thank you for calling out the padding that was bugging me and I couldnt figure it out and thought it was just an anomaly lol.  As of now I opted for a button to fix the alignment issue and to keep some consistency with other settings screen that take the user to another screen.

2022-01-24 21:00 UTC, JBassett requested changes
Just a tiny thing about the `init`.  You should just use the built in one, not create your own.

2022-01-25 00:57 UTC, JBassett approved these changes

2022-01-25 00:58 UTC, merged