Check that connection is not null before attempting to send a message
home-assistant/android pull request #2263
Opened 2022-02-12 02:52 UTC by dshokouhi

## Summary

Fixes the following sentry errors by performing a null check before attempting to send the message:

```
java.lang.NullPointerException: null
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl$sendMessage$2.invokeSuspend(WebSocketRepositoryImpl.kt:313)
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl$sendMessage$2.invoke
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl$sendMessage$2.invoke
    at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:100)
    at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:146)
    at kotlinx.coroutines.TimeoutKt.withTimeoutOrNull(Timeout.kt:103)
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.sendMessage(WebSocketRepositoryImpl.kt:304)
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.access$sendMessage(WebSocketRepositoryImpl.kt:56)
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl$handleClosingSocket$2.invokeSuspend(WebSocketRepositoryImpl.kt:400)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```
slightly different errors
```
java.lang.NullPointerException: null
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl$sendMessage$2.invokeSuspend(WebSocketRepositoryImpl.kt:308)
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl$sendMessage$2.invoke
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl$sendMessage$2.invoke
    at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:100)
    at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:146)
    at kotlinx.coroutines.TimeoutKt.withTimeoutOrNull(Timeout.kt:103)
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.sendMessage(WebSocketRepositoryImpl.kt:304)
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.subscribeToEventsForType(WebSocketRepositoryImpl.kt:182)
    at io.homeassistant.companion.android.common.data.websocket.impl.WebSocketRepositoryImpl.getAreaRegistryUpdates(WebSocketRepositoryImpl.kt:170)
    at io.homeassistant.companion.android.controls.HaControlsProviderService$createPublisherFor$1$1$request$1.invokeSuspend(HaControlsProviderService.kt:108)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
    at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

## Screenshots

## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#

## Any other notes

2022-02-13 19:51 UTC, JBassett requested changes
This isn't going to do what you expect.  We should get out of the habit of using `!!` and instead use `?`

2022-02-13 20:09 UTC, dshokouhi commented
> This isn't going to do what you expect. We should get out of the habit of using `!!` and instead use `?`

ok I think I got it as expected? I can't really reproduce the issue so hard to tell if it fixes the issue. What I can do is confirm the websocket connection continues to send messages :)

2022-02-13 22:56 UTC, jpelgrom commented
> I can't really reproduce the issue

I've actually seen this error a lot while working on error handling for the Wear OS app and the latest commit to fix a race condition (f10f5f0b33be4d17cbd54634f8c852e20c0c93f5) made this even easier to trigger. Try launching two or more websocket requests at the same time by using different jobs, while in airplane mode.
```
    ioScope.launch {
        webSocketRepository.getAreaRegistry()
    }
    ioScope.launch {
        webSocketRepository.getDeviceRegistry()
    }
```
Because no connection triggers `onFailure` in `WebSocketRepositoryImpl`, the `connected` Job that monitors whether there is a connection or not is completed. However, the other request is waiting for being able to use `connect()` because of the mutex, and will be executed before the job is reset because that is _also_ waiting for the mutex. For the second request, `connect()` only checks for completion, not for completion without cancellation, and because of that it will return `true` and the app continues assuming there is a connection, which gives us the NPE.

Fixed in the Wear OS error handling PR by [including a check for job cancelled or not](https://github.com/home-assistant/android/pull/2261/commits/8f64e97d7cd7f98fc8778f754036330086c531af), but still good to improve the code here in case there's another edge case that hasn't been found yet.

2022-02-17 03:28 UTC, JBassett approved these changes

2022-02-17 03:28 UTC, merged