Fix SIM sensor crash
home-assistant/android pull request #2389
Opened 2022-03-21 16:45 UTC by dshokouhi

## Summary

Fixes: #2386 by checking that display name is not null and also catching any other potential failures

## Screenshots

## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#

## Any other notes

2022-03-21 17:23 UTC, JBassett requested changes

2022-03-21 17:23 UTC, JBassett commented on app/src/main/java/io/homeassistant/companion/android/sensors/PhoneStateSensorManager.kt
> +                            else attrs["data roaming"] = "disable"
```suggestion
                             attrs["data roaming"] = if (info.dataRoaming == SubscriptionManager.DATA_ROAMING_ENABLE) "enable" else "disable"
```

2022-03-21 17:23 UTC, JBassett commented on app/src/main/java/io/homeassistant/companion/android/sensors/PhoneStateSensorManager.kt
> +                            displayName = info.displayName.toString()
```suggestion
                        displayName = info.displayName?.toString() ?: displayName
```

2022-03-21 19:52 UTC, jpelgrom commented
FYI, I've opened another PR #2391 to prevent crashing the UI as well. Still a good idea to catch and handle errors in the manager itself though :)

2022-03-21 19:56 UTC, dshokouhi commented
> FYI, I've opened another PR #2391 to prevent crashing the UI as well. Still a good idea to catch and handle errors in the manager itself though :)

I agree we need it in both places, good idea!

2022-03-23 00:14 UTC, JBassett approved these changes

2022-03-23 00:14 UTC, merged