Set Loading State for Entities
home-assistant/android pull request #3502
Opened 2023-04-29 18:09 UTC by googlvalenzuela

## Summary
Declare executing state of an entity based on verb states.
This allows Android Auto scenarios to show that the entity is loading and provid
`
fun <T> Entity<T>.isExecuting()=  state.endsWith("ing")
`

## Screenshots
<img width="783" alt="Screenshot 2023-04-29 at 11 07 35 AM" src="https://user-images.githubusercontent.com/127877770/235317691-ceb619c4-9d84-41cc-8ecf-4f81465e3af9.png">
e feedback for the user about the state on which the entity is in.

2023-05-03 23:11 UTC, marazmarci commented
> States is an open system and can be any value. While I think this works for the currently supported domains, to prevent showing the 'loading' indicator unintentionally IMO the `isExecuting` function should check against a list of known executing states instead to be safe.

a list of known states can be found here I think: https://github.com/home-assistant/core/blob/ef9bcd9285980385eede726e15aa1e7d20238eee/homeassistant/const.py#L330

2023-05-13 02:42 UTC, JBassett requested changes
I agree, just checking if the state ends in ing is too broad.

2023-05-15 03:58 UTC, googlvalenzuela commented
Thanks for the feedback, Ive updated the code.

2023-05-15 18:05 UTC, jpelgrom commented on common/src/main/java/io/homeassistant/companion/android/common/data/integration/Entity.kt
> +    "disarming" -> true
If you include `disarming`, also add `arming`

2023-05-15 18:28 UTC, googlvalenzuela commented
Added Armig.

2023-05-15 18:42 UTC, jpelgrom approved these changes

2023-05-20 18:57 UTC, JBassett approved these changes

2023-05-20 18:57 UTC, merged