mobile_app_notification_cleared for wearos
home-assistant/android pull request #4035
Opened 2023-11-28 20:06 UTC by JosephAbbey

## Summary

Moved the `NotificationDeleteRecieve` to common and added it to the WearOS app.

## Screenshots

## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#

## Any other notes

I have not been able to run the WearOS app at all on the simulator (even without any of my changes) so I haven't been able to test it but it compiles.

2023-11-28 23:26 UTC, dshokouhi commented
I think for this PR we also need to make a manifest change to add the receiver to the`wear manifest like it is added for the main app manifest

what issue are you running into with the emulator?

2023-11-30 18:58 UTC, JosephAbbey commented
Ok, I have added the receiver to the manifest.

The entire simulator just would crash as soon as the app started loading, I wasn't too worried because I have only just installed the wearos virtual device and I hoped someone else could test this change.

2023-11-30 19:25 UTC, JosephAbbey commented
I can't get logs because the whole simulator crashes and the logcat logs disappear to quickly. I haven't setup the notification service yet but the app won't even start anyway.

2023-12-01 20:08 UTC, dshokouhi commented on wear/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
> +    private fun handleDeleteIntent(
We should move this and the same method from phone to `common` as well as the function is nearly identical here.

2023-12-01 22:00 UTC, dshokouhi requested changes
Looks good to me and tested it on my watch locally. Still needs docs update before we can merge. Please submit a PR to add a mention in the Wear OS docs.

We need to update this page: https://companion.home-assistant.io/docs/wear-os/#notifications

2023-12-02 08:45 UTC, dshokouhi approved these changes

2023-12-13 19:45 UTC, JBassett approved these changes

2023-12-13 19:45 UTC, merged